
export enum SensorTypes {
  MAINLINE__TEMPERATURE_IN_SENSOR = 'MAINLINE__TEMPERATURE_IN_SENSOR',
  MAINLINE__PRESSURE_IN_SENSOR = 'MAINLINE__PRESSURE_IN_SENSOR',
  MAINLINE__TEMPERATURE_OUT_SENSOR = 'MAINLINE__TEMPERATURE_OUT_SENSOR',
  MAINLINE__PRESSURE_OUT_SENSOR = 'MAINLINE__PRESSURE_OUT_SENSOR',

  HEATING_STATION__VALVE_IN_SENSOR = 'HEATING_STATION__VALVE_IN_SENSOR',
  HEATING_STATION__PUMP_IN_SENSOR = 'HEATING_STATION__PUMP_IN_SENSOR',
  HEATING_STATION__VALVE_OUT_SENSOR = 'HEATING_STATION__VALVE_IN_SENSOR',
  HEATING_STATION__PUMP_OUT_SENSOR = 'HEATING_STATION__PUMP_IN_SENSOR',
}

export enum SocketEvents {
  SENSOR_STATE = 'SENSOR_STATE',
  SENSOR_GROUP_STATE = 'SENSOR_GROUP_STATE',
}


export interface ISensorStateSocketData {
  id: string,
  parameter: string,
}
