
export enum SensorTypes {
  MAINLINE__TEMPERATURE_IN_SENSOR = 'MAINLINE__TEMPERATURE_IN_SENSOR',
  MAINLINE__PRESSURE_IN_SENSOR = 'MAINLINE__PRESSURE_IN_SENSOR',
  MAINLINE__TEMPERATURE_OUT_SENSOR = 'MAINLINE__TEMPERATURE_OUT_SENSOR',
  MAINLINE__PRESSURE_OUT_SENSOR = 'MAINLINE__PRESSURE_OUT_SENSOR',

  HEATING_STATION__VALVE_IN_SENSOR = 'HEATING_STATION__VALVE_IN_SENSOR',
  HEATING_STATION__PUMP_IN_SENSOR = 'HEATING_STATION__PUMP_IN_SENSOR',
  HEATING_STATION__VALVE_OUT_SENSOR = 'HEATING_STATION__VALVE_OUT_SENSOR',
  HEATING_STATION__PUMP_OUT_SENSOR = 'HEATING_STATION__PUMP_OUT_SENSOR',
}

export enum SocketEvents {
  SENSOR_STATE = 'SENSOR_STATE',
  SENSOR_GROUP_STATE = 'SENSOR_GROUP_STATE',
  HEATING_STATION_INITIAL_SENSORS_STATE = 'HEATING_STATION_INITIAL_SENSORS_STATE',
}

export type SensorValue = number | boolean;

export interface ISensorStateSocketData {
  id: string,
  type: SensorTypes,
  value: SensorValue,
}
